"""empty message

Revision ID: 63195cd6aab1
Revises: c8c5a4c12b5a
Create Date: 2023-10-16 16:25:15.399200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63195cd6aab1'
down_revision = 'c8c5a4c12b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_table_user1_id_profile_table', type_='foreignkey')
        batch_op.drop_constraint('fk_conversation_table_user2_id_profile_table', type_='foreignkey')
        batch_op.drop_column('user2_id')
        batch_op.drop_column('user1_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user2_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_conversation_table_user2_id_profile_table', 'profile_table', ['user2_id'], ['id'])
        batch_op.create_foreign_key('fk_conversation_table_user1_id_profile_table', 'profile_table', ['user1_id'], ['id'])

    # ### end Alembic commands ###
