"""empty message

Revision ID: 81291b25e351
Revises: 0986a4954d8b
Create Date: 2023-10-19 10:59:29.404458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81291b25e351'
down_revision = '0986a4954d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_table_profile_id_profile_table'), 'profile_table', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_table_profile_id_profile_table'), type_='foreignkey')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
