"""empty message

Revision ID: 85e10f3542e3
Revises: 
Create Date: 2023-10-20 13:13:02.699826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e10f3542e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_table')),
    sa.UniqueConstraint('username', name=op.f('uq_profile_table_username'))
    )
    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_table.id'], name=op.f('fk_post_table_profile_id_profile_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_table'))
    )
    op.create_table('comment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], name=op.f('fk_comment_table_post_id_post_table')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_table.id'], name=op.f('fk_comment_table_profile_id_profile_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_table')
    op.drop_table('post_table')
    op.drop_table('profile_table')
    # ### end Alembic commands ###
