"""empty message

Revision ID: c8c5a4c12b5a
Revises: 
Create Date: 2023-10-16 16:02:42.493080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c5a4c12b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['profile_table.id'], name=op.f('fk_conversation_table_user1_id_profile_table')),
    sa.ForeignKeyConstraint(['user2_id'], ['profile_table.id'], name=op.f('fk_conversation_table_user2_id_profile_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_table.id'], name=op.f('fk_message_table_conversation_id_conversation_table')),
    sa.ForeignKeyConstraint(['user_id'], ['profile_table.id'], name=op.f('fk_message_table_user_id_profile_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_table')
    op.drop_table('conversation_table')
    op.drop_table('profile_table')
    # ### end Alembic commands ###
